In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from IPython.display import display
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [2]:
df = pd.read_csv('heart.csv')
df.describe()

age         sex          cp      trtbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg    thalachh        exng     oldpeak         slp         caa  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

            thall      output  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [3]:
x = df.loc[:,~df.columns.isin(['output'])]
y = df.loc[:,df.columns.isin(['output'])]

In [4]:
train_x, test_x,train_y,test_y = train_test_split(x,y,test_size=0.2,random_state=42)

In [5]:
x.corr().style.applymap(lambda x: 'color : red' if x >0.7 else 'color : white')

In [6]:
model = svm.SVC(kernel= 'linear') #default rbf
model.fit(train_x,train_y)
print('---linear---')
display(confusion_matrix(model.predict(test_x),test_y))
model = svm.SVC(kernel= 'rbf') #default rbf
model.fit(train_x,train_y)
print('---rbf---')
display(confusion_matrix(model.predict(test_x),test_y))
model = svm.SVC(kernel= 'poly') #default rbf
model.fit(train_x,train_y)
print('---poly---')
display(confusion_matrix(model.predict(test_x),test_y))

C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


---linear---


array([[25,  4],
       [ 4, 28]], dtype=int64)

---rbf---


C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[15,  4],
       [14, 28]], dtype=int64)

---poly---


C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[20,  5],
       [ 9, 27]], dtype=int64)

In [7]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [8]:
LE = LabelEncoder()
temp = train['Activity'].copy()
train['Activity'] = LE.fit_transform(train['Activity'])
print(set(zip(temp,train['Activity'])))
temp = test['Activity'].copy()
test['Activity'] = LE.fit_transform(test['Activity'])
print(set(zip(temp,test['Activity'])))

{('LAYING', 0), ('STANDING', 2), ('WALKING_DOWNSTAIRS', 4), ('WALKING', 3), ('SITTING', 1), ('WALKING_UPSTAIRS', 5)}
{('LAYING', 0), ('STANDING', 2), ('WALKING_DOWNSTAIRS', 4), ('WALKING', 3), ('SITTING', 1), ('WALKING_UPSTAIRS', 5)}


In [9]:
train_x = train.loc[:,~train.columns.isin(['Activity'])]
train_y = train.loc[:,train.columns.isin(['Activity'])]
test_x = train.loc[:,~test.columns.isin(['Activity'])]
test_y = train.loc[:,test.columns.isin(['Activity'])]


In [10]:
model = svm.SVC(kernel='rbf')
model.fit(train_x,train_y)
display(confusion_matrix(model.predict(test_x),test_y))
print(model.score(test_x,test_y))

C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[1407,   10,    0,    0,    0,    0],
       [   0, 1108,  105,    0,    0,    0],
       [   0,  167, 1269,    0,    0,    0],
       [   0,    0,    0, 1221,    3,    6],
       [   0,    0,    0,    1,  975,    3],
       [   0,    1,    0,    4,    8, 1064]], dtype=int64)

0.9581066376496191


In [11]:
model = svm.SVC(kernel='poly')
model.fit(train_x,train_y)
display(confusion_matrix(model.predict(test_x),test_y))
print(model.score(test_x,test_y))

C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[1404,    3,    0,    0,    0,    0],
       [   0, 1192,   83,    0,    0,    0],
       [   0,   90, 1291,    0,    0,    0],
       [   1,    0,    0, 1219,   45,   44],
       [   0,    0,    0,    0,  933,    7],
       [   2,    1,    0,    7,    8, 1022]], dtype=int64)

0.9604189336235038


In [12]:
model = svm.SVC(kernel='linear')
model.fit(train_x,train_y)
display(confusion_matrix(model.predict(test_x),test_y))
print(model.score(test_x,test_y))

C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[1407,    0,    0,    0,    0,    0],
       [   0, 1267,   25,    0,    0,    0],
       [   0,   19, 1349,    0,    0,    0],
       [   0,    0,    0, 1226,    0,    0],
       [   0,    0,    0,    0,  986,    0],
       [   0,    0,    0,    0,    0, 1073]], dtype=int64)

0.9940152339499456


In [35]:
df = pd.read_csv('log2.csv')
display(df)
display(df.describe())
display(df.corr().style.applymap(lambda x: 'color :red ' if x > 0.7 else  'color : white'))

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
0            57222                53            54587                    53   
1            56258              3389            56258                  3389   
2             6881             50321            43265                 50321   
3            50553              3389            50553                  3389   
4            50002               443            45848                   443   
...            ...               ...              ...                   ...   
65527        63691                80            13237                    80   
65528        50964                80            13485                    80   
65529        54871               445                0                     0   
65530        54870               445                0                     0   
65531        54867               445                0                     0   

      Action    Bytes  Bytes Sent  Bytes Received  Packets  \
0      allow      177          94              83        2   
1      allow     4768        1600            3168       19   
2      allow      238         118             120        2   
3      allow     3327        1438            1889       15   
4      allow    25358        6778           18580       31   
...      ...      ...         ...             ...      ...   
65527  allow      314         192             122        6   
65528  allow  4680740       67312         4613428     4675   
65529   drop       70          70               0        1   
65530   drop       70          70               0        1   
65531   drop       70          70               0        1   

       Elapsed Time (sec)  pkts_sent  pkts_received  
0                      30          1              1  
1                      17         10              9  
2                    1199          1              1  
3                      17          8              7  
4                      16         13             18  
...                   ...        ...            ...  
65527                  15          4              2  
65528                  77        985           3690  
65529                   0          1              0  
65530                   0          1              0  
65531                   0          1              0  

[65532 rows x 12 columns]

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
count  65532.000000      65532.000000     65532.000000          65532.000000   
mean   49391.969343      10577.385812     19282.972761           2671.049930   
std    15255.712537      18466.027039     21970.689669           9739.162278   
min        0.000000          0.000000         0.000000              0.000000   
25%    49183.000000         80.000000         0.000000              0.000000   
50%    53776.500000        445.000000      8820.500000             53.000000   
75%    58638.000000      15000.000000     38366.250000            443.000000   
max    65534.000000      65535.000000     65535.000000          65535.000000   

              Bytes    Bytes Sent  Bytes Received       Packets  \
count  6.553200e+04  6.553200e+04    6.553200e+04  6.553200e+04   
mean   9.712395e+04  2.238580e+04    7.473815e+04  1.028660e+02   
std    5.618439e+06  3.828139e+06    2.463208e+06  5.133002e+03   
min    6.000000e+01  6.000000e+01    0.000000e+00  1.000000e+00   
25%    6.600000e+01  6.600000e+01    0.000000e+00  1.000000e+00   
50%    1.680000e+02  9.000000e+01    7.900000e+01  2.000000e+00   
75%    7.522500e+02  2.100000e+02    4.490000e+02  6.000000e+00   
max    1.269359e+09  9.484772e+08    3.208818e+08  1.036116e+06   

       Elapsed Time (sec)      pkts_sent  pkts_received  
count        65532.000000   65532.000000   65532.000000  
mean            65.833577      41.399530      61.466505  
std            302.461762    3218.871288    2223.332271  
min              0.000000       1.000000       0.000000  
25%              0.000000       1.000000       0.000000  
50%             15.000000       1.000000       1.000000  
75%             30.000000       3.000000       2.000000  
max          10824.000000  747520.000000  327208.000000

In [36]:
LE = LabelEncoder()
cols = ['Source Port', 'Destination Port', 'NAT Source Port', 'NAT Destination Port', 'Action']
for col in cols :
    temp = df[col]
    df[col] = LE.fit_transform(df[col])
    if col == 'Action' :
        print(set(zip(temp,df[col])))

{('deny', 1), ('drop', 2), ('allow', 0), ('reset-both', 3)}


In [15]:
df['Action'].value_counts()
df2 = df.drop(columns=['Bytes','Packets','pkts_sent','pkts_received','Source Port','Destination Port','NAT Source Port','NAT Destination Port'])

In [16]:
display(df2.corr().style.applymap(lambda x: 'color :red ' if x > 0.7 else  'color : white'))

In [17]:
x = df2.loc[:,~df2.columns.isin(['Action'])]
y = df2.loc[:,df2.columns.isin(['Action'])]


In [18]:
VIF = pd.DataFrame(columns=['VIF'],index = x.columns)
VIF['VIF'] = [variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
VIF.style.applymap(lambda x : 'color : yellow' if x >= 10 else 'color : white')

In [19]:
train_x, test_x , train_y, test_y = train_test_split(x,y,test_size=0.3,random_state=42)

In [20]:
model = svm.SVC()
model.fit(train_x,train_y)
confusion_matrix(model.predict(test_x),test_y)

C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[11330,  4485,  3830,    15],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0]], dtype=int64)

In [22]:
model = svm.SVC(kernel = 'linear')
model.fit(train_x,train_y)
confusion_matrix(model.predict(test_x),test_y)

C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[11315,     2,     0,     3],
       [   15,  4483,  3830,    12],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0]], dtype=int64)

In [21]:
model = svm.SVC(kernel = 'poly')
model.fit(train_x,train_y)
confusion_matrix(model.predict(test_x),test_y)

C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[11330,  4485,  3830,    15],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0]], dtype=int64)

In [23]:
model = svm.SVC(kernel = 'poly',degree=2)
model.fit(train_x,train_y)
confusion_matrix(model.predict(test_x),test_y)

C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[11330,  4485,  3830,    15],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0]], dtype=int64)

In [30]:
df3 = df2[df2['Action'] != 3]
x2 = df3.loc[:,~df3.columns.isin(['Action'])]
y2 = df3.loc[:,df3.columns.isin(['Action'])]
train_x, test_x , train_y, test_y = train_test_split(x2,y2,test_size=0.3,random_state=42)


In [31]:
model = svm.SVC(kernel = 'linear')
model.fit(train_x,train_y)
confusion_matrix(model.predict(test_x),test_y)

C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[11276,     3,     0],
       [   12,  4465,  3888],
       [    0,     0,     0]], dtype=int64)

In [32]:
model = svm.SVC()
model.fit(train_x,train_y)
confusion_matrix(model.predict(test_x),test_y)

C:\Users\2022040601\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[11288,  4468,  3888],
       [    0,     0,     0],
       [    0,     0,     0]], dtype=int64)

In [41]:
dict1 = df['Source Port'].value_counts().to_dict()
dict2 = df['Destination Port'].value_counts().to_dict()

In [77]:
df4 = df.copy()
df4['Source Port'] = df4['Source Port'].map(dict1)
df4['Destination Port'] = df4['Destination Port'].map(dict2)
df4['Receive_rate'] =  df4['Bytes Received'] /df4['Bytes']
x = df4.loc[:,['Source Port','Destination Port','Receive_rate','Elapsed Time (sec)']]
y = df4['Action']

In [87]:
VIF = pd.DataFrame(columns=['VIF'],index = x.columns)
VIF['VIF'] = [variance_inflation_factor(x.values,i) for i in range(len(x.columns))]
display(x)
VIF.style.applymap(lambda x : 'color : yellow' if x >= 10 else 'color : white')


Source Port  Destination Port  Receive_rate  Elapsed Time (sec)
0                3             15414      0.468927                  30
1                8               176      0.664430                  17
2              177                17      0.504202                1199
3                5               176      0.567779                  17
4                7             11684      0.732708                  16
...            ...               ...           ...                 ...
65527            3              4035      0.388535                  15
65528            3              4035      0.985619                  77
65529            1             12891      0.000000                   0
65530            3             12891      0.000000                   0
65531            3             12891      0.000000                   0

[65532 rows x 4 columns]

In [79]:
train_x, test_x , train_y, test_y = train_test_split(x,y,test_size=0.3,random_state=42)

In [80]:
model = svm.SVC()
model.fit(train_x,train_y)
confusion_matrix(model.predict(test_x),test_y)

array([[9669,   13,    0,    0],
       [1661, 4463,    0,   15],
       [   0,    9, 3830,    0],
       [   0,    0,    0,    0]], dtype=int64)

In [83]:
print(model.intercept_)

[3.37871653e+00 2.05127055e+01 1.00969140e+00 2.34225490e+00
 1.01193372e+00 2.17463509e-03]


In [60]:
df5 = df.copy()
df5['Receive_rate'] =  df5['Bytes Received'] /df5['Bytes']
x = df5.loc[:,['Source Port','Destination Port','Receive_rate','Elapsed Time (sec)']]
y = df5['Action']
train_x, test_x , train_y, test_y = train_test_split(x,y,test_size=0.3,random_state=42)
model = svm.SVC()
model.fit(train_x,train_y)
confusion_matrix(model.predict(test_x),test_y)

array([[10282,   927,  3830,     7],
       [ 1048,  3558,     0,     8],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0]], dtype=int64)

In [74]:
z = pd.concat([test_x,test_y],axis= 1)
z[z['Action'] == 1]#['Destination Port'].unique()

Source Port  Destination Port  Receive_rate  Elapsed Time (sec)  Action
43957        10396              3216           0.0                   0       1
63448         5094              1888           0.0                   0       1
12432         1439              2573           0.0                   0       1
7029         16951               255           0.0                   0       1
14572         7004              2636           0.0                   0       1
...            ...               ...           ...                 ...     ...
11099        17319              1147           0.0                   0       1
53215        17051               427           0.0                   0       1
10389         5422              1888           0.0                   0       1
21351          740              1017           0.0                   0       1
7262         16951               255           0.0                   0       1

[4485 rows x 5 columns]